"""empty message

Revision ID: 1088b661e644
Revises: 
Create Date: 2021-05-16 15:25:51.032769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1088b661e644'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('restaurant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('restaurant_place', sa.VARCHAR(length=255), nullable=False),
    sa.Column('restaurant_category', sa.VARCHAR(length=255), nullable=False),
    sa.Column('restaurant_piority', sa.Integer(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_token', sa.VARCHAR(length=45), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('login_token'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('poll',
    sa.Column('poll_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), nullable=False),
    sa.Column('shared_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('place', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('poll_id'),
    sa.UniqueConstraint('poll_id')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['poll.poll_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('vote',
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_vote', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.poll_id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('poll_id', 'user_id', 'restaurant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('category')
    op.drop_table('poll')
    op.drop_table('user')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
